name: CI tests

on:
  push:
  workflow_call:
  workflow_dispatch:

env:
  DATABASE_URL: postgres://postgres:dummy@localhost:5432/test

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  security-dependencies:
    name: "Security: bundle-audit dependencies"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: /tmp/rails-template.tar
          key: ${{ github.sha }}-rails-template
      - run: docker load --input /tmp/rails-template.tar
      - run: docker run --rm rails-template:latest bundle exec bundle-audit check --update
  security-audit:
    name: "Security: Brakeman audit"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: /tmp/rails-template.tar
          key: ${{ github.sha }}-rails-template
      - run: docker load --input /tmp/rails-template.tar
      - run: docker run --rm rails-template:latest bundle exec brakeman -q -w2
  lint:
    name: "Linting: Rubocop"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: /tmp/rails-template.tar
          key: ${{ github.sha }}-rails-template
      - run: docker load --input /tmp/rails-template.tar
      - run: docker run -e DATABASE_URL="${{ env.DATABASE_URL }}" --rm rails-template:latest bundle exec rubocop
  unit-tests:
    name: "Unit tests: RSpec"
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        # TODO: Fix reuse of POSTGRES_VERSION
        # image: "postgres:${{ env.POSTGRES_VERSION }}"
        image: postgres:16
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: dummy
          POSTGRES_VERSION: "16"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: /tmp/rails-template.tar
          key: ${{ github.sha }}-rails-template
      - run: docker load --input /tmp/rails-template.tar
      - run: |
          docker run \
            --network="host" \
            -e DATABASE_URL="${{ env.DATABASE_URL }}" \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --rm rails-template bash -c "bin/rails db:environment:set RAILS_ENV=test && bundle exec rspec"
  integration-tests:
    name: "Integration tests: Cucumber"
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: dummy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: /tmp/rails-template.tar
          key: ${{ github.sha }}-rails-template
      - run: docker load --input /tmp/rails-template.tar
      - run: |
          docker run \
            --network="host" \
            -e DATABASE_URL="${{ env.DATABASE_URL }}" \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --rm rails-template bundle exec cucumber
